package az.growlab.LoanApp.enums;

public enum ActionStatus {

    WAITING_FOR_IDENTITY_APPROVE,
    IDENTITY_CHECK_APPROVED,
    WAITING_FOR_INITIAL_APPROVE,
    INITIAL_CHECK_APPROVED,
    WAITING_FOR_FINAL_APPROVE,
    FINAL_CHECK_APPROVED;

}
